export const PATHS = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  PROFILE: "/profile",
  ADMIN: {
    ROOT: "/admin",
    DASHBOARD: "/admin/dashboard",
    USERS: "/admin/users",
    USER_DETAIL: "/admin/users/:userId",
    MEALS: "/admin/meals",
    ORDERS: "/admin/orders",
    DELIVERIES: "/admin/deliveries",
    ANALYTICS: "/admin/analytics",
    SUPPORT: "/admin/support",
    CATEGORIES: "/admin/categories",
    INVENTORY: "/admin/inventory",
    COUPONS: "/admin/coupons",
    PAYMENTS: "/admin/payments",
    PAYMENT_GATEWAY: "/admin/payment-gateway",
  },
  CUSTOMER: {
    ROOT: "/customer",
    DASHBOARD: "/customer/dashboard",
    MEALS: "/customer/meals",
    CHECKOUT: "/customer/checkout",
    ORDERS: "/customer/orders",
    ADDRESSES: "/customer/addresses",
    LOYALTY: "/customer/loyalty",
    SUPPORT: "/customer/support",
    REVIEWS: "/customer/reviews",
  },
  DELIVERY: {
    ROOT: "/delivery",
    DASHBOARD: "/delivery/dashboard",
    ASSIGNMENTS: "/delivery/assignments",
  },
  PAYMENT: {
    CHECKOUT: "/payment/checkout",
    SUCCESS: "/payment/success",
    CANCEL: "/payment/cancel",
  },
  NOT_FOUND: "*",
} as const;
